try w/ updated permissions

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -33,6 +33,16 @@ jobs:
       - name: Install Playwright browsers
         run: make e2e-setup-ci
 
+      - name: Ensure permissions for blob-report directory
+        run: |
+          mkdir -p ./e2e/blob-report
+          chmod -R 777 ./e2e/blob-report
+
+      - name: Verify Blob Report Directory
+        run: |
+            echo "Contents of blob-report directory on host:"
+            ls -R ./e2e/blob-report || echo "blob-report directory not found"
+
       - name: Run e2e tests (Shard ${{ matrix.shard }}/${{ matrix.total_shards }})
         run: |
           make e2e-test \
@@ -41,10 +51,7 @@ jobs:
             CURRENT_SHARD=${{ matrix.shard }} \
             TOTAL_SHARDS=${{ matrix.total_shards }}
 
-      - name: Copy Blob Report from Docker Container
-        run: docker cp playwright-e2e-container:/e2e/blob-report ./e2e/blob-report
-
-      - name: Verify Blob Report Directory
+      - name: Verify Blob Report Directory 2
         run: |
           echo "Contents of blob-report directory on host:"
           ls -R ./e2e/blob-report || echo "blob-report directory not found"
