add verify blob dir step

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -38,6 +38,11 @@ jobs:
             CURRENT_SHARD: ${{ matrix.shard }}
         run: make e2e-test APP_NAME=${{ inputs.app_name }} BASE_URL=${{ inputs.service_endpoint }}
 
+      - name: Verify Blob Report Directory
+        run: |
+          echo "Contents of blob-report directory:"
+          ls -R blob-report || echo "blob-report directory not found"
+
       - name: Upload Blob Report
         if: always()
         uses: actions/upload-artifact@v4
@@ -53,24 +58,25 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v3
-    - uses: actions/setup-node@v3
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
 
-    - name: Install dependencies
-      run: npm ci
 
-    - name: Download All Blob Reports
-      uses: actions/download-artifact@v4
-      with:
-        name: all-blob-reports-shard-*
-        path: all-blob-reports
+      - name: Install dependencies
+        run: npm ci
 
-    - name: Merge Blob Reports into HTML
-      run: npx playwright merge-reports --reporter html ./all-blob-reports
+      - name: Download All Blob Reports
+        uses: actions/download-artifact@v4
+        with:
+          name: all-blob-reports-shard-*
+          path: all-blob-reports
 
-    - name: Upload Merged HTML Report
-      uses: actions/upload-artifact@v4
-      with:
-        name: merged-html-report
-        path: all-blob-reports/playwright-report
-        retention-days: 7
+      - name: Merge Blob Reports into HTML
+        run: npx playwright merge-reports --reporter html ./all-blob-reports
+
+      - name: Upload Merged HTML Report
+        uses: actions/upload-artifact@v4
+        with:
+          name: merged-html-report
+          path: all-blob-reports/playwright-report
+          retention-days: 7
