map blob-report dir on e2e-test cmd

diff --git a/.github/workflows/e2e-tests.yml b/.github/workflows/e2e-tests.yml
--- a/.github/workflows/e2e-tests.yml
+++ b/.github/workflows/e2e-tests.yml
@@ -48,7 +48,7 @@ jobs:
         run: |
           mkdir -p ./e2e/blob-report
           echo "Contents of blob-report directory:"
-          ls -R blob-report || echo "blob-report directory not found"
+          ls -R ./e2e/blob-report || echo "blob-report directory not found"
 
       - name: Upload Blob Report
         if: always()
